"""Compatibility shim for batch output aggregation helpers."""

from llm_conceptual_modeling.hf_batch.outputs import (
    _aggregated_analysis_spec,
    _analysis_value_columns,
    _budget_analysis_specs,
    _combined_analysis_spec,
    _combined_factorial_spec,
    _decoding_factor_columns,
    _evaluate_and_factorial_aggregate_output,
    _evaluate_raw_output,
    _load_raw_rows_frame,
    _write_analysis_outputs,
    _write_replication_budget_outputs,
    evaluate_algo3_results,
    evaluate_connection_results_file,
    run_algo1_factorial_analysis,
    run_algo2_factorial_analysis,
    run_algo3_factorial_analysis,
    run_generalized_factorial_analysis,
    write_aggregated_outputs,
    write_grouped_metric_stability,
    write_output_variability_analysis,
    write_replication_budget_analysis,
)

__all__ = [
    "_aggregated_analysis_spec",
    "_analysis_value_columns",
    "_budget_analysis_specs",
    "_combined_analysis_spec",
    "_combined_factorial_spec",
    "_decoding_factor_columns",
    "_evaluate_and_factorial_aggregate_output",
    "_evaluate_raw_output",
    "_load_raw_rows_frame",
    "_write_analysis_outputs",
    "_write_replication_budget_outputs",
    "evaluate_connection_results_file",
    "evaluate_algo3_results",
    "run_algo1_factorial_analysis",
    "run_algo2_factorial_analysis",
    "run_algo3_factorial_analysis",
    "run_generalized_factorial_analysis",
    "write_grouped_metric_stability",
    "write_output_variability_analysis",
    "write_replication_budget_analysis",
    "write_aggregated_outputs",
]
