#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SSH_COMMAND="${1:-}"
LOCAL_REPO_DIR="${2:-}"
LOCAL_RESULTS_DIR="${3:-}"

export DRAIN_ROOT_NAME_CONTAINS="${DRAIN_ROOT_NAME_CONTAINS:-olmo}"
export DRAIN_STATE_FILE="${DRAIN_STATE_FILE:-${LOCAL_RESULTS_DIR:-${LOCAL_REPO_DIR:-$SCRIPT_DIR/../..}/results}/drain-olmo-state.json}"
export DRAIN_PHASE="${DRAIN_PHASE:-all}"
export DRAIN_POLL_SECONDS="${DRAIN_POLL_SECONDS:-${OLMO_DRAIN_POLL_SECONDS:-30}}"
export DRAIN_STALE_AFTER_SECONDS="${DRAIN_STALE_AFTER_SECONDS:-${OLMO_RUNNING_ROOT_STALE_SECONDS:-3600}}"
export DRAIN_QUICK_RESUME_SCRIPT="${DRAIN_QUICK_RESUME_SCRIPT:-${OLMO_QUICK_RESUME_SCRIPT:-$SCRIPT_DIR/quick_resume_from_ssh.sh}}"
export LOCAL_RESULTS_SYNC_INTERVAL_SECONDS="${LOCAL_RESULTS_SYNC_INTERVAL_SECONDS:-${OLMO_LOCAL_RESULTS_SYNC_INTERVAL_SECONDS:-30}}"
export LOCAL_RESULTS_SYNC_RSYNC_TIMEOUT_SECONDS="${LOCAL_RESULTS_SYNC_RSYNC_TIMEOUT_SECONDS:-${OLMO_LOCAL_RESULTS_SYNC_RSYNC_TIMEOUT_SECONDS:-300}}"

exec bash "$SCRIPT_DIR/drain_remaining_from_ssh.sh" "$SSH_COMMAND" "$LOCAL_REPO_DIR" "$LOCAL_RESULTS_DIR" "$DRAIN_ROOT_NAME_CONTAINS"
